services:

  postgres:
    image: postgres:16-alpine
    container_name: expense-manager-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: expense_manager
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U expense_user -d expense_manager"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: expense-manager-backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: expense-manager-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data:
