"""add transaction categories and types

Revision ID: d2016650597a
Revises: 6b2c8ff5f72b
Create Date: 2026-08-30 05:06:09.065087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2016650597a'
down_revision: Union[str, Sequence[str], None] = '6b2c8ff5f72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_categories_id'), 'transaction_categories', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_categories_name'), 'transaction_categories', ['name'], unique=True)
    op.create_index(op.f('ix_transaction_categories_slug'), 'transaction_categories', ['slug'], unique=True)
    op.create_table('transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_types_category_id'), 'transaction_types', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_types_id'), 'transaction_types', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_types_name'), 'transaction_types', ['name'], unique=False)
    op.create_index(op.f('ix_transaction_types_slug'), 'transaction_types', ['slug'], unique=True)
    op.drop_index(op.f('ix_transaction_details_account_id'), table_name='transaction_details')
    op.drop_index(op.f('ix_transaction_details_category_id'), table_name='transaction_details')
    op.drop_index(op.f('ix_transaction_details_id'), table_name='transaction_details')
    op.drop_index(op.f('ix_transaction_details_transaction_id'), table_name='transaction_details')
    op.drop_index(op.f('ix_transaction_details_user_id'), table_name='transaction_details')
    op.drop_table('transaction_details')
    op.add_column('transactions', sa.Column('transaction_type_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_type_id'), 'transactions', ['transaction_type_id'], unique=False)
    op.drop_constraint(op.f('transactions_category_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'transaction_types', ['transaction_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_transactions_transaction_type_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.drop_column('transactions', 'transaction_type_id')
    op.create_table('transaction_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('transaction_details_account_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('transaction_details_category_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('transaction_details_transaction_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transaction_details_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_details_pkey'))
    )
    op.create_index(op.f('ix_transaction_details_user_id'), 'transaction_details', ['user_id'], unique=False)
    op.create_index(op.f('ix_transaction_details_transaction_id'), 'transaction_details', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_transaction_details_id'), 'transaction_details', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_details_category_id'), 'transaction_details', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_details_account_id'), 'transaction_details', ['account_id'], unique=False)
    op.drop_index(op.f('ix_transaction_types_slug'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_name'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_id'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_category_id'), table_name='transaction_types')
    op.drop_table('transaction_types')
    op.drop_index(op.f('ix_transaction_categories_slug'), table_name='transaction_categories')
    op.drop_index(op.f('ix_transaction_categories_name'), table_name='transaction_categories')
    op.drop_index(op.f('ix_transaction_categories_id'), table_name='transaction_categories')
    op.drop_table('transaction_categories')
    # ### end Alembic commands ###
